---@class HareConfigAppearance
---@field netrw HareConfigAppearanceNetrw
---@field color_scheme HareConfigAppearanceColorScheme
---
---@class HareConfigAppearanceNetrw
---@field enabled boolean
---
---@class HareConfigAppearanceColorScheme
---@field mode 'dark' | 'light' | 'system'
---@field light_scheme string
---@field dark_scheme string
