---@class HareConfigEditor
---@field appearance HareConfigEditorAppearance
---@field general HareConfigEditorGeneral
---
---@class HareConfigEditorAppearance
---@field line_number HareConfigEditorAppearanceLineNumber
---@field sign_column HareConfigEditorAppearanceSignColumn
---@field cursor HareConfigEditorAppearanceCursor
---@field cursor_insert HareConfigEditorAppearanceCursorInsert
---@field color_column HareConfigEditorAppearanceColorColumn
---@field cursor_line HareConfigEditorAppearanceColorLine
---@field fill_chars string
---
---@class HareConfigEditorAppearanceLineNumber
---@field enabled boolean
---@field relative boolean
---@field highlight? HighlightGroup
---@field cursor_highlight? HighlightGroup
---
---@class HareConfigEditorAppearanceSignColumn
---@field enabled boolean
---
---@class HareConfigEditorAppearanceCursor
---@field highlight? HighlightGroup
---
---@class HareConfigEditorAppearanceCursorInsert
---@field highlight? HighlightGroup
---
---@class HareConfigEditorAppearanceColorColumn
---@field enabled boolean
---@field highlight? HighlightGroup
---@field disabled_filetypes string[]
---
---@class HareConfigEditorAppearanceColorLine
---@field enabled boolean
---@field highlight? HighlightGroup
---
---@class HareConfigEditorGeneral
---@field tab HareConfigEditorGeneralTab
---
---@class HareConfigEditorGeneralTab
---@field expand_with_spaces boolean
---@field width integer
---@field display_width integer
---@field shift_width integer
