---@class HareConfEditor
---@field appearance HareConfEditorAppearance
---@field general HareConfEditorLang
---@field lang table<string, HareConfEditorLang>
---
---@class HareConfEditorAppearance
---@field line_number HareConfEditorAppearanceLineNumber
---@field sign_column HareConfEditorAppearanceSignColumn
---@field cursor HareConfEditorAppearanceCursor
---@field cursor_insert HareConfEditorAppearanceCursorInsert
---@field cursor_line HareConfEditorAppearanceColorLine
---@field fill_chars string
---
---@class HareConfEditorAppearanceLineNumber
---@field enabled boolean
---@field relative boolean
---@field highlight? HighlightGroup
---@field cursor_highlight? HighlightGroup
---
---@class HareConfEditorAppearanceSignColumn
---@field enabled boolean
---
---@class HareConfEditorAppearanceCursor
---@field highlight? HighlightGroup
---
---@class HareConfEditorAppearanceCursorInsert
---@field highlight? HighlightGroup
---
---@class HareConfEditorAppearanceColorLine
---@field enabled boolean
---@field highlight? HighlightGroup
---
---@class HareConfEditorLang
---@field tab? HareConfEditorLangTab
---@field color_column? HareConfEditorLangColorColumn
---@field format_on_save? boolean
---@field treesitter? HareConfEditorLangTreesitter
---@field lsp? HareConfEditorLangLsp
---@field linter? HareConfEditorLangLinter
---@field formatter? HareConfEditorLangFormatter
---
---@class HareConfEditorLangTab
---@field expand_with_spaces? boolean
---@field width? integer
---@field display_width? integer
---@field shift_width? integer
---
---@class HareConfEditorLangColorColumn
---@field enabled? boolean
---@field width? integer
---@field highlight? HighlightGroup
---
---@class HareConfEditorLangTreesitter
---@field name? string
---
---@class HareConfEditorLangLsp
---@field enabled? boolean
---@field name? string
---
---@class HareConfEditorLangLinter
---@field enabled? boolean
---@field name? string
---
---@class HareConfEditorLangFormatter
---@field enabled? boolean
---@field name? string
